# Generated by Django 3.2.8 on 2021-12-06 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingridients',
            new_name='ingredients',
        ),
    ]
