# Generated by Django 3.2.8 on 2021-12-06 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_ingridients_recipe_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='descripion',
            new_name='description',
        ),
    ]
