# Generated by Django 3.2.8 on 2021-12-08 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_descripion_recipe_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('breakfast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakfasts', to='app.recipe')),
                ('dinner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinners', to='app.recipe')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='app.recipe')),
            ],
        ),
    ]
