# Generated by Django 3.2.8 on 2021-12-08 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_daymenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='daymenu',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='app.user'),
            preserve_default=False,
        ),
    ]
