# Generated by Django 3.2.8 on 2021-12-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=20)),
                ('block', models.IntegerField()),
            ],
        ),
    ]
