# Generated by Django 3.2.8 on 2021-12-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_block_zoneproduct_blocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField(default=0)),
                ('ratio', models.FloatField(default=0)),
            ],
        ),
    ]
