# Generated by Django 3.2.8 on 2021-12-20 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_zonemenuitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zonemenuitem',
            old_name='item',
            new_name='product',
        ),
    ]
