# Generated by Django 3.2.8 on 2021-12-20 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_item_zonemenuitem_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ZoneMenuItem',
            new_name='Item',
        ),
    ]
