# Generated by Django 3.2.8 on 2021-12-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_zonemenuitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonemenu',
            name='tags',
            field=models.CharField(default='meal', max_length=50),
        ),
    ]
