# Generated by Django 3.2.8 on 2021-12-22 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_zonemenu_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('breakfast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.zonemenu')),
            ],
        ),
    ]
