# Generated by Django 3.2.8 on 2021-12-22 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_zoneday'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoneday',
            name='snackI',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='snacksI', to='app.zonemenu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zoneday',
            name='breakfast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakfasts', to='app.zonemenu'),
        ),
    ]
