# Generated by Django 3.2.8 on 2021-12-22 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20211222_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoneday',
            name='dinners',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dinners', to='app.zonemenu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zoneday',
            name='meal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='app.zonemenu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zoneday',
            name='snackII',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='snacksII', to='app.zonemenu'),
            preserve_default=False,
        ),
    ]
