# Generated by Django 3.2.8 on 2021-12-22 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20211222_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zoneday',
            old_name='dinners',
            new_name='dinner',
        ),
    ]
