# Generated by Django 3.2.8 on 2021-12-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_dinners_zoneday_dinner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='protein', max_length=20),
        ),
    ]
